\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{lettear}[A LaTeX Letter Class of Teagoslavia]
\LoadClass[11pt,a5paper]{letter} % extend article class



\input{\string~/projects/tex-macros/general_macros/general_typesetting_letter.sty}
%\input{\string~/projects/tex-macros/general_macros/hyperlinks_and_references.sty}
\input{\string~/projects/tex-macros/general_macros/figures.sty}
\input{\string~/projects/tex-macros/general_macros/tables.sty}
%\input{\string~/projects/tex-macros/general_macros/table_of_x.sty}
\input{\string~/projects/tex-macros/general_macros/footnotes.sty}
\input{\string~/projects/tex-macros/general_macros/lists.sty}
\input{\string~/projects/tex-macros/general_macros/mathematical.sty}
\input{\string~/projects/tex-macros/general_macros/code_format.sty}
\input{\string~/projects/tex-macros/general_macros/chemical.sty}
\input{\string~/projects/tex-macros/general_macros/miscellaneous_letter.sty}


%%%%%% Put any custom features after this line! %%%%%%
