% !TEX TS-program = pdflatex
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{arteacleBib}[A LaTeX Article Class of Teagoslavia]

\LoadClass[11pt,a4paper]{article}
\ProcessOptions\relax

\input{\string~/tex-macros/general_macros/general_typesetting.sty}
\input{\string~/tex-macros/general_macros/hyperlinks_and_references_cite.sty}%create a references.bib to have bibtex!  see https://tex.stackexchange.com/questions/524468/biblatex-not-generating-in-text-citations-or-references, https://www.reddit.com/r/LaTeX/comments/epftjv/bibliography_not_loading_references_using_apacite/, https://tex.stackexchange.com/a/394471/181375
\input{\string~/tex-macros/general_macros/figures.sty}
\input{\string~/tex-macros/general_macros/tables.sty}
\input{\string~/tex-macros/general_macros/table_of_x.sty}
\input{\string~/tex-macros/general_macros/footnotes.sty}
\input{\string~/tex-macros/general_macros/lists.sty}
\input{\string~/tex-macros/general_macros/mathematical.sty}
\input{\string~/tex-macros/general_macros/chemical.sty}
\input{\string~/tex-macros/general_macros/miscellaneous.sty}