\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{lettear}[A LaTeX Letter Class of Teagoslavia]
\LoadClass[11pt, a5paper]{letter} % extend article class

\input{jakewilliami/tex-macros/macros/letter/general.sty}
\input{jakewilliami/tex-macros/macros/colours.sty}
\input{jakewilliami/tex-macros/macros/figures.sty}
\input{jakewilliami/tex-macros/macros/tables.sty}
\input{jakewilliami/tex-macros/macros/footnotes.sty}
\input{jakewilliami/tex-macros/macros/mathematical.sty}
\input{jakewilliami/tex-macros/macros/units.sty}
\intpu{jakewilliami/tex-macros/macros/letter/signature.sty}
\input{jakewilliami/tex-macros/macros/miscellaneous.sty}


%%%%%% Put any custom features after this line! %%%%%%
